baseURL = "/"
languageCode = "en-us"
title = "Very Epic"
theme = "anubis"


[params]
    author = "o7 Fire"

    dateFormat = "2006-09-02"
    paginationSinglePost = true
    style = "auto"
    #mainSections = [ "posts" ] # which sections should be on index/main page
    #sectionsWithFullContentOnListPage = [ "notes" ] # for which sections content should be displayed on list pages
    readMore = false # show read more button
    readNextPosts = 5  # show 5 related posts, 0 by default
    disableSummary = false
    toc = true # display Table of Contents
    tocWordCount = 300 # ...when a post is longer than 300 words
    copyCodeButton = true # true by default
    rssAsSocialIcon = false
    mathjax = true # https://www.mathjax.org/
    # utteranc.es support
    utterancesRepo = ""  # mandatory
    utterancesTheme = "" # optional
    utterancesIssue = "" # optional
    utterancesLabel = "" # optional
